### ISSUE TITLE
How to build it for android？

### ISSUE THREAD

**Issue by jekinleeph** [netty/netty-incubator-codec-quic#403] opened 2022-05-16 07:20 UTC
I use "mvnw package -P android" to package the project, but it failed. Are there any build documents about this project？

**Comment by lxl53535** [comment] 2023-02-24 16:43
the option "android" is netty_quiche
the opetion "android-arm64-v8a"、 "android-armeabi-v7a"  ...  is optional
![image](https://user-images.githubusercontent.com/10113198/221233195-8eca4895-deab-498b-8bc6-1beec99507cb.png)
add "ANDROID_NDK_HOME"、"ANDROID_HOME",  it can be optimized by volumes
install cargo-ndk

![image](https://user-images.githubusercontent.com/10113198/221234394-ac752068-e2e9-4f22-bfcf-c6ad87577920.png)
![image](https://user-images.githubusercontent.com/10113198/221234599-271aefad-f72c-4e0f-8e28-ef8e3e473e28.png)
add "build-android" option



![image](https://user-images.githubusercontent.com/10113198/221235124-12fcc4e7-b8a7-4f4c-8110-5446736e8702.png)

edit pom , remove these rows


cd ${project.basedir}   
run docker-compose -f docker/docker-compose.centos-7.yaml -f docker/docker-compose.centos-7.18.yaml run build-android

wait ....



test ...
![image](https://user-images.githubusercontent.com/10113198/221236563-7384899c-0a17-4148-80f2-b99b77107f9a.png)
![image](https://user-images.githubusercontent.com/10113198/221236808-d0e126a4-c529-4223-8ece-7330da0ee60a.png)

**Comment by Snowmaze-dev** [comment] 2023-07-09 03:50
Hi, I’m wondering if anyone can build aars for all abis (or at least for arm64-v8a) for me. I tried to build it on windows but I encountered a lot of errors that I don’t know how to fix. Make for some reason can't build boringssl. I would really appreciate your help.

**Comment by JBou** [comment] 2023-07-10 21:12
I just fixed building for Android in #553, it was not working since #493.

Please take a look in the [ci-build.yml GitHub workflow](https://github.com/netty/netty-incubator-codec-quic/blob/main/.github/workflows/ci-build.yml#L163-L217
) for the steps you have to make and the dependencies you need to install. Once you have installed all the dependencies, start the build with `mvnw clean package -Dandroid`. This builds the `aar` library for Android that contains native libraries for all 4 [Android ABIs](https://developer.android.com/ndk/guides/abis)

In the meantime, you can download the built Android library from my fork from the artifacts tab, where I built it today using the workflow above using the newest version available: https://github.com/JBou/netty-incubator-codec-quic/actions/runs/5505784359

I was not able to build it on Windows, I used [WSL](https://learn.microsoft.com/en-us/windows/wsl/) for development and building it. I can confirm it worked after the dependencies and prerequisites were all installed correctly.

I try to update #322 in the next time and if it is possible for @normanmaurer to include the Android artifact in the maven repo, a lot of people would not need to build it themselves, and it would make it less difficult to use.

**Comment by normanmaurer** [comment] 2023-07-11 01:04
Let me close this one... Not sure about also releasing for android yet.

**Closed by normanmaurer** 2023-07-11 01:04 UTC
