### ISSUE TITLE
Quic server very slow compared to TCP

### ISSUE THREAD

**Issue by DanielAlmeidaJoao** [netty/netty-incubator-codec-quic#575] opened 2023-09-04 23:03 UTC
Hello,

I have a simple netty client-server application to stream a 1GB file, and I noticed that the one using QUIC is extremely lower than
the one using TCP, for example, the TCP server application takes 4 seconds to read all the bytes of the file from the client, while the QUIC server takes 8 seconds.

What is happening? Is quic supposed to be this much slower than TCP ?
Have you tested the speed of this quic-netty-incubator implementation vs the TCP offered by netty ?

**Comment by normanmaurer** [comment] 2023-10-19 09:55
Yes I have tested it and yes its slower then TCP. That said it's also not fair to compare both as QUIC also includes encryption etc.

**Comment by normanmaurer** [comment] 2023-10-19 09:55
Beside this you also want to use GSO etc

**Comment by normanmaurer** [comment] 2023-11-02 07:57
This might be a duplicate of https://github.com/netty/netty-incubator-codec-quic/issues/598

**Closed by normanmaurer** 2023-11-02 07:57 UTC

**Comment by DanielAlmeidaJoao** [comment] 2023-12-14 14:03
What is a GSO ?
